services:
  carstradeapi:
    image: ${DOCKER_REGISTRY-}carstradeapi
    container_name: CarsTradeAPI
    build:
      context: .
      dockerfile: CarsTradeAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - carstradeapi_database
      - carstradeapi_redis

  carstradeapi_database:
    image: postgres:latest
    container_name: carstradeapiDatabase
    environment:
      - POSTGRES_DB=CarsTrade
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mototaz12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  carstradeapi_redis:
    image: redis:latest
    container_name: carstradeapi_redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: