services:
  carstradeapi:
    image: ${DOCKER_REGISTRY-}carstradeapi
    container_name: CarsTradeAPI
    build:
      context: .
      dockerfile: CarsTradeAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - carstradeapi_database
      - carstradeapi_redis

  carstradeworker:
    image: ${DOCKER_REGISTRY-}carstradeworker
    container_name: CarsTradeWorker
    build:
      context: .
      dockerfile: CarsTradeWorker/Dockerfile
    depends_on:
      - carstradeapi_database
      - carstradeapi_rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings_DefaultConnection: "Host=carstradeapi_database;Database=CarsTrade;Username=postgres;Password=mototaz12"
      RabbitMq__Host: "carstradeapi_rabbitmq"

  carstradeapi_database:
    image: postgres:latest
    container_name: carstradeapiDatabase
    environment:
      - POSTGRES_DB=CarsTrade
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mototaz12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  carstradeapi_redis:
    image: redis:latest
    container_name: carstradeapi_redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  carstradeapi_rabbitmq:
    image: rabbitmq:3.12-management
    container_name: carstradeapi_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  postgres_data: